### ISSUE TITLE
Replace ryanj/pillar-base with a simple hapi app 

### ISSUE THREAD

**Issue by lance** [bucharest-gold/origin-s2i-nodejs#10]
We need a basic Hapi application that we can use as an example, and a foundation for Node.js examples on OpenShift. See: https://github.com/bucharest-gold/origin-s2i-nodejs/tree/master/nodejs.org#usage

Currently that is https://github.com/ryanj/pillar-base but we should have something of our own that we can build on.

**Comment by helio-frota** [comment]
https://github.com/bucharest-gold/s2i-nodejs#the-app

```
/
/info
/status
```

**Comment by lance** [comment]
Excellent!
