### ISSUE TITLE
Immediate error about conditional binary operator expected

### ISSUE THREAD

**Issue by lholmquist** [bucharest-gold/origin-s2i-nodejs#13]
https://gist.github.com/lholmquist/ac30beacc8e25da9b21edd5b767811a9

For me, it happened on master,   ran `make test` and immediately got this

**Comment by helio-frota** [comment]
I really don't remember if my test was yesterday or today.
https://github.com/bucharest-gold/entente/issues/126#issuecomment-278314323
/me assuming yesterday but with your feedback, now I have no idea :D

**Comment by lholmquist** [comment]
closing,  I didn't have the latest master commit
