### ISSUE TITLE
Add a save-artifiacts script to the s2i build

### ISSUE THREAD

**Issue by lance** [bucharest-gold/origin-s2i-nodejs#19]
This would allow developers to use the --incremental flag when building their application image. The result would be that the `./node_modules` directory is preserved between builds so that that phase of the assembly doesn't have to get repeated for every build if not needed.

**Comment by helio-frota** [comment]
I'm doing this and is working:

save-artifacts:
```bash
#!/bin/bash

tar -C /opt/app-root/src -cf - node_modules
```

assemble:
```bash
if [ "$(ls /tmp/artifacts 2>/dev/null)" ]; then
  echo "---> Restore things..."
  mv /tmp/artifacts/* ./
fi
```

**Comment by helio-frota** [comment]
https://github.com/bucharest-gold/origin-s2i-nodejs/commit/0c500a517bfbef3fbe2c4bbc8baa48a3d043b330
