### ISSUE TITLE
Test building Openshift apps using the new images

### ISSUE THREAD

**Issue by lance** [bucharest-gold/origin-s2i-nodejs#28]
@helio-frota you are already doing this to some extent with your work on the `save-images` script. I think it would be useful to have several different example applications bundled with the repo.

**Comment by helio-frota** [comment]
in progress...

https://github.com/bucharest-gold/s2i-nodejs#using-openshift-origin-client-tools

https://github.com/bucharest-gold/origin-s2i-nodejs/issues/39

**Comment by lance** [comment]
@helio-frota I think we should be all set with this. If you want to outline what you have done to test these here, we can close it.

**Comment by helio-frota** [comment]
After the fix: https://github.com/bucharest-gold/origin-s2i-nodejs/pull/40
The apps works fine:
https://github.com/bucharest-gold/s2i-nodejs#using-oc-client-with-oc-cluster-up
