### ISSUE TITLE
Submit PR to https://github.com/redhat-helloworld-msa/bonjour

### ISSUE THREAD

**Issue by lance** [bucharest-gold/origin-s2i-nodejs#29]
Once we publish and test our images, the MSA demo app should be updated to use a modern node with one of these images.

**Comment by lholmquist** [comment]
will also submit a PR to the frontend microservice.

**Comment by lholmquist** [comment]
PR for bonjour service https://github.com/redhat-helloworld-msa/bonjour/pull/18

**Comment by lholmquist** [comment]
PR for the frontend service https://github.com/redhat-helloworld-msa/frontend/pull/9

**Comment by lholmquist** [comment]
Both have been merged,  closing now
