### ISSUE TITLE
Project Restructure - Dev-Mode - where is this package.json

### ISSUE THREAD

**Issue by lholmquist** [bucharest-gold/origin-s2i-nodejs#30]
https://github.com/bucharest-gold/origin-s2i-nodejs/tree/project-restructure#note-define-your-own-dev_mode

@lance  Where is the package.json it refers to

**Comment by lance** [comment]
The information is now found in the top level README.md, although it is still a little confusing. For now I will close this. If we need to open another to deal with the actual text we can do that in another issue.
