### ISSUE TITLE
s2i run script should exit after run_node

### ISSUE THREAD

**Issue by lance** [bucharest-gold/origin-s2i-nodejs#44]
There are two conditions for the `run_node` command in the `run` script that is used by s2i. The script should exit after the command if the `if` condition is true here https://github.com/bucharest-gold/origin-s2i-nodejs/blob/master/s2i/run#L18 to prevent it from being run twice.

**Comment by helio-frota** [comment]
https://github.com/bucharest-gold/origin-s2i-nodejs/pull/52
