### ISSUE TITLE
generate_container_user should not prevent an app from being deployed

### ISSUE THREAD

**Issue by lance** [bucharest-gold/origin-s2i-nodejs#45]
This line https://github.com/bucharest-gold/origin-s2i-nodejs/blob/master/contrib/etc/generate_container_user#L10 can fail. We should check to be sure all of the conditions are met before attempting to run it. E.g. the target directory should exist and `/etc/passwd` should be readable.

**Comment by helio-frota** [comment]
I'm not 100% sure but I guess `/etc/passwd` is always readable by default.

https://github.com/bucharest-gold/origin-s2i-nodejs/pull/51
