### ISSUE TITLE
ONBUILD npm install should come after ONBUILD COPY .

### ISSUE THREAD

**Issue by rafabene** [bucharest-gold/origin-s2i-nodejs#46]
ONBUILD npm install should come after ONBUILD COPY .
Users might already have 'node_modules/' folder locally, so "npm install" could take less time to be execute if it was copied previously from the sources.

**Comment by helio-frota** [comment]
https://github.com/bucharest-gold/origin-s2i-nodejs/commit/4a12054678a2beabea87342a27b63c54c19009fd
