### ISSUE TITLE
Make npm install not so verbose

### ISSUE THREAD

**Issue by lholmquist** [bucharest-gold/origin-s2i-nodejs#53]
For some reason, our images are very verbose when doing the npm install,  compared to the openshift node version 4 image

referenced gist:
https://gist.github.com/david-martin/6f0f93d87c44e3f5300695b847f03902

I was guessing it had something to do with https://github.com/bucharest-gold/origin-s2i-nodejs/blob/master/s2i/assemble#L56 

but making that just `npm install` instead of `npm install -d` didn't do anything when i created a new image locally and used the s2i command.

So i'm not really sure where it could be. unless my computer is trolling me

**Comment by lholmquist** [comment]
this is my branch where i tried, https://github.com/lholmquist/origin-s2i-nodejs/tree/less-npm-install-logs

**Comment by helio-frota** [comment]
thanks!
