### ISSUE TITLE
nodejs.org GPG release keys changed

### ISSUE THREAD

**Issue by sherl0cks** [bucharest-gold/origin-s2i-nodejs#56]
https://github.com/bucharest-gold/origin-s2i-nodejs/blob/master/Dockerfile#L34-L41 no longer matches https://github.com/nodejs/node#release-team

**Comment by helio-frota** [comment]
Thanks for reporting the issue.
landed here:
https://github.com/bucharest-gold/origin-s2i-nodejs/commit/0f8eb5baaf76dd53894a1578511c4acf4c7fc142
