### ISSUE TITLE
Support a matrix of operating system and node version images

### ISSUE THREAD

**Issue by lance** [bucharest-gold/origin-s2i-nodejs#62]
Now that we have what appear to be reasonable Node.js images for centos7, it's time to expand our horizons a bit. I would like to restructure this project so that we can produce a full set of images (both ONBUILD and s2i) for Node 4, 5, 6, 7, etc. with each of the following operating container images:

* CentOS
* Fedora
* RHEL
* rhel7-atomic

I have created a [branch](https://github.com/lance/origin-s2i-nodejs/tree/atomic-base) where I have the `rhel7-atomic` image working. However to really do this correctly, we should probably rethink the structure and build process. Since each OS has different requirements, there should probably be a base `Dockerfile` for each OS - probably within an OS-specific directory. 

During this reworking, we need to also be thinking about versioning for the repo, and what our process is so that when we have this completed we can tag the repo with 1.0 or whatever. As @lholmquist mentioned earlier, we could also perhaps tag our docker images on hub.docker.com with the commit hash for the repo.

**Comment by helio-frota** [comment]
https://github.com/bucharest-gold/origin-s2i-nodejs/commit/42baffac6a7bb56dc42759415e8bb718e62c7d9a
