### ISSUE TITLE
Investigate and maybe remove nss_wrapper from tests

### ISSUE THREAD

**Issue by lance** [bucharest-gold/origin-s2i-nodejs#9]
During the test phase of the build, nss_wrapper is installed. But for some reason, the `yum install nss_wrapper` command does not install it. The problem is described here https://bugzilla.redhat.com/show_bug.cgi?id=1297729. We may need to submit a patch to the openshift team for the base image. But honestly, I am not sure.

Read more about nss_wrapper here https://cwrap.org/nss_wrapper.html

**Comment by helio-frota** [comment]
@lance this was fixed ?
I can't find nothing about `nss_wrapper` on logs.

```
hf@hf-ThinkPad-T440:~$ grep "nss_wrapper" foo.txt 
hf@hf-ThinkPad-T440:~$ 
```

**Comment by lance** [comment]
@helio-frota yes, we didn't remove it as you know. All is good now.
